# Generated by Django 4.1.7 on 2023-04-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='start_count',
            new_name='star_count',
        ),
    ]
