# Generated by Django 4.1.7 on 2023-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_rename_customer_resetpassword_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
