# Generated by Django 4.1.7 on 2023-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='used_coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0),
        ),
    ]
